Sudoku example v2
jenetics/jenetics pull request #816
Opened 2022-01-09 19:30 UTC by alex-cornejo

* Contains an implementation of a GA for the sudoku.
* Contains a custom crossover.
* Provides four different boards for testing.
* Important sections of code are documented.
* A SudokuGrid class that abstracts logic of sudoku penalties

This is a PR v2 of https://github.com/jenetics/jenetics/pull/810

2022-01-09 19:35 UTC, alex-cornejo commented
I am open to any suggestion aiming to improve this implementation :)
Thanks so much for the support.

2022-01-13 20:12 UTC, jenetics requested changes
Thank you for the new version. Looks way better. I only have a view comments ;-)

2022-01-13 20:12 UTC, jenetics commented on jenetics.example/src/main/java/io/jenetics/example/sudoku/SudokuUtil.java
> +	public static final int[][] BOARD1 = {
With a `Board` class it is also possible to do some precondition check and throw an `IllegalArgumentException` for invalid boards.

2022-01-18 17:13 UTC, jenetics approved these changes
Locks good. Will merge into r7.0.0 branch.

2022-01-18 17:24 UTC, merged